//! Embedded real block textures — GPL v2, from github.com/elhedran/SimpleRP
//! (commit 341c49484fc8b7138d6d5ff60f48fcf59fb4bf81), see CREDITS.md and
//! assets/textures/LICENSE-SimpleRP. Compiled directly into the binary via
//! include_bytes!, matching this project's established no-runtime-file-
//! dependency pattern (blocks.json/items.json are include_str!'d the same
//! way, the old procedural atlas needed no files at all).

/// Raw PNG bytes for an embedded block texture by name (matches the second
/// element of `engine_core::mesh::ATLAS_TILES` entries that use
/// `TileSource::Png`). `None` for an unknown name — checked once at atlas
/// build time (`create_atlas`), not a runtime path a player can hit.
pub fn png_bytes(name: &str) -> Option<&'static [u8]> {
    Some(match name {
        "bedrock" => include_bytes!("../assets/textures/blocks/bedrock.png"),
        "brick" => include_bytes!("../assets/textures/blocks/brick.png"),
        "cactus_side" => include_bytes!("../assets/textures/blocks/cactus_side.png"),
        "clay" => include_bytes!("../assets/textures/blocks/clay.png"),
        "coal_ore" => include_bytes!("../assets/textures/blocks/coal_ore.png"),
        "cobblestone" => include_bytes!("../assets/textures/blocks/cobblestone.png"),
        "cobblestone_mossy" => include_bytes!("../assets/textures/blocks/cobblestone_mossy.png"),
        "diamond_ore" => include_bytes!("../assets/textures/blocks/diamond_ore.png"),
        "dirt" => include_bytes!("../assets/textures/blocks/dirt.png"),
        "emerald_ore" => include_bytes!("../assets/textures/blocks/emerald_ore.png"),
        "glass" => include_bytes!("../assets/textures/blocks/glass.png"),
        "glass_black" => include_bytes!("../assets/textures/blocks/glass_black.png"),
        "glass_blue" => include_bytes!("../assets/textures/blocks/glass_blue.png"),
        "glass_brown" => include_bytes!("../assets/textures/blocks/glass_brown.png"),
        "glass_cyan" => include_bytes!("../assets/textures/blocks/glass_cyan.png"),
        "glass_gray" => include_bytes!("../assets/textures/blocks/glass_gray.png"),
        "glass_green" => include_bytes!("../assets/textures/blocks/glass_green.png"),
        "glass_light_blue" => include_bytes!("../assets/textures/blocks/glass_light_blue.png"),
        "glass_lime" => include_bytes!("../assets/textures/blocks/glass_lime.png"),
        "glass_magenta" => include_bytes!("../assets/textures/blocks/glass_magenta.png"),
        "glass_orange" => include_bytes!("../assets/textures/blocks/glass_orange.png"),
        "glass_pink" => include_bytes!("../assets/textures/blocks/glass_pink.png"),
        "glass_purple" => include_bytes!("../assets/textures/blocks/glass_purple.png"),
        "glass_red" => include_bytes!("../assets/textures/blocks/glass_red.png"),
        "glass_silver" => include_bytes!("../assets/textures/blocks/glass_silver.png"),
        "glass_white" => include_bytes!("../assets/textures/blocks/glass_white.png"),
        "glass_yellow" => include_bytes!("../assets/textures/blocks/glass_yellow.png"),
        "gold_ore" => include_bytes!("../assets/textures/blocks/gold_ore.png"),
        "grass_side" => include_bytes!("../assets/textures/blocks/grass_side.png"),
        "hardened_clay" => include_bytes!("../assets/textures/blocks/hardened_clay.png"),
        "hardened_clay_stained_black" => include_bytes!("../assets/textures/blocks/hardened_clay_stained_black.png"),
        "hardened_clay_stained_blue" => include_bytes!("../assets/textures/blocks/hardened_clay_stained_blue.png"),
        "hardened_clay_stained_brown" => include_bytes!("../assets/textures/blocks/hardened_clay_stained_brown.png"),
        "hardened_clay_stained_cyan" => include_bytes!("../assets/textures/blocks/hardened_clay_stained_cyan.png"),
        "hardened_clay_stained_gray" => include_bytes!("../assets/textures/blocks/hardened_clay_stained_gray.png"),
        "hardened_clay_stained_green" => include_bytes!("../assets/textures/blocks/hardened_clay_stained_green.png"),
        "hardened_clay_stained_light_blue" => include_bytes!("../assets/textures/blocks/hardened_clay_stained_light_blue.png"),
        "hardened_clay_stained_lime" => include_bytes!("../assets/textures/blocks/hardened_clay_stained_lime.png"),
        "hardened_clay_stained_magenta" => include_bytes!("../assets/textures/blocks/hardened_clay_stained_magenta.png"),
        "hardened_clay_stained_orange" => include_bytes!("../assets/textures/blocks/hardened_clay_stained_orange.png"),
        "hardened_clay_stained_pink" => include_bytes!("../assets/textures/blocks/hardened_clay_stained_pink.png"),
        "hardened_clay_stained_purple" => include_bytes!("../assets/textures/blocks/hardened_clay_stained_purple.png"),
        "hardened_clay_stained_red" => include_bytes!("../assets/textures/blocks/hardened_clay_stained_red.png"),
        "hardened_clay_stained_silver" => include_bytes!("../assets/textures/blocks/hardened_clay_stained_silver.png"),
        "hardened_clay_stained_white" => include_bytes!("../assets/textures/blocks/hardened_clay_stained_white.png"),
        "hardened_clay_stained_yellow" => include_bytes!("../assets/textures/blocks/hardened_clay_stained_yellow.png"),
        "iron_ore" => include_bytes!("../assets/textures/blocks/iron_ore.png"),
        "lapis_ore" => include_bytes!("../assets/textures/blocks/lapis_ore.png"),
        "leaves_acacia_opaque" => include_bytes!("../assets/textures/blocks/leaves_acacia_opaque.png"),
        "leaves_big_oak_opaque" => include_bytes!("../assets/textures/blocks/leaves_big_oak_opaque.png"),
        "leaves_birch_opaque" => include_bytes!("../assets/textures/blocks/leaves_birch_opaque.png"),
        "leaves_jungle_opaque" => include_bytes!("../assets/textures/blocks/leaves_jungle_opaque.png"),
        "leaves_oak_opaque" => include_bytes!("../assets/textures/blocks/leaves_oak_opaque.png"),
        "leaves_spruce_opaque" => include_bytes!("../assets/textures/blocks/leaves_spruce_opaque.png"),
        "log_acacia" => include_bytes!("../assets/textures/blocks/log_acacia.png"),
        "log_big_oak" => include_bytes!("../assets/textures/blocks/log_big_oak.png"),
        "log_birch" => include_bytes!("../assets/textures/blocks/log_birch.png"),
        "log_jungle" => include_bytes!("../assets/textures/blocks/log_jungle.png"),
        "log_oak" => include_bytes!("../assets/textures/blocks/log_oak.png"),
        "log_spruce" => include_bytes!("../assets/textures/blocks/log_spruce.png"),
        "obsidian" => include_bytes!("../assets/textures/blocks/obsidian.png"),
        "planks_acacia" => include_bytes!("../assets/textures/blocks/planks_acacia.png"),
        "planks_big_oak" => include_bytes!("../assets/textures/blocks/planks_big_oak.png"),
        "planks_birch" => include_bytes!("../assets/textures/blocks/planks_birch.png"),
        "planks_jungle" => include_bytes!("../assets/textures/blocks/planks_jungle.png"),
        "planks_oak" => include_bytes!("../assets/textures/blocks/planks_oak.png"),
        "planks_spruce" => include_bytes!("../assets/textures/blocks/planks_spruce.png"),
        "redstone_ore" => include_bytes!("../assets/textures/blocks/redstone_ore.png"),
        "sand" => include_bytes!("../assets/textures/blocks/sand.png"),
        "sandstone_normal" => include_bytes!("../assets/textures/blocks/sandstone_normal.png"),
        "stone" => include_bytes!("../assets/textures/blocks/stone.png"),
        "stonebrick" => include_bytes!("../assets/textures/blocks/stonebrick.png"),
        "stonebrick_cracked" => include_bytes!("../assets/textures/blocks/stonebrick_cracked.png"),
        "stonebrick_mossy" => include_bytes!("../assets/textures/blocks/stonebrick_mossy.png"),
        _ => return None,
    })
}
